### PR TITLE
change getBoolean to parseBoolean in ParserUtils

### LINKED ISSUE #498: ParserUtils 中 Boolean.getBoolean 疑 是 Boolean.parseBoolean 的 误 写
Boolean.getBoolean疑是Boolean.parseBoolean的误写，导致一直返回false
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java#L56
同样的场景，下文使用的是Boolean.parseBoolean
https://github.com/sofastack/sofa-boot/blob/58a438812f537b3e8e4c9270fd86baee69dcf4fd/sofa-boot-project/sofa-boot-core/runtime-sofa-boot/src/main/java/com/alipay/sofa/runtime/spi/util/ParserUtils.java#L58

### PR DESCRIPTION
**Pull request by glmapper**
Fix #498

### CODE REVIEW

**Comment by khotyn** [comment]
Can you add some testcase?

**Comment by glmapper** [comment]
> Can you add some testcase?

Currently, SOFABoot does not define attribute tags such as lazy-init / depend-on in [sofaboot-xsd]. It is not suitable for executing this logic by mock.

But by analyzing the code, getBoolean(name) takes the name value from the system parameter as the parse result, parseBoolen(value) uses the value directly as the result, ParserUtils is intended to parse the tag's property value, so what you expect here is The current string, not the key of a system parameter

**Comment by khotyn** [comment]
@glmapper 那是不是可以把这部分的代码删除掉？

**Comment by glmapper** [comment]
Associated with this discussion https://github.com/sofastack/sofa-boot/issues/520

**Review by alaneuler — APPROVED** [review]
LGTM

**Pull request merged**
