### PR TITLE
Add configuration for local env(#861)

### PR DESCRIPTION
**Pull request by aaronlinv**
1. 也判断下是不是 Eclipse 启动的（判断下是否能加载到 Eclipse 的 class）
Eclipse 似乎并不是像 IDEA 一样使用 agent 方式启动，所以没有找到 Eclipse 的 class，参考了一些资料[How to detect that code is running inside eclipse IDE](https://stackoverflow.com/questions/2468059/how-to-detect-that-code-is-running-inside-eclipse-ide)，没有找到比较靠谱的判断方式，所以没有实现该功能

2. 加个配置项，如果配了就认为是通过 IDE 启动的
增加了相关的配置项与其对应的测试类

### CODE REVIEW

**Comment by seeflood** [comment]
Thanks for your contribution!
@alaneuler  Can u help review this pr ?

**Comment by alaneuler** [comment]
1. plz format the code via `mvn package`
2. we want a configuration for specifying local env, not logging (`isLocalEnv` returns `true` if setting the configuration to true)
3. set aside the eclipse detecting as there seems no reliable way of detecting

**Comment by aaronlinv** [comment]
@alaneuler 
Thanks, only need to detect the specified environment variable in the `isLocalEnv` method?

**Comment by alaneuler** [comment]
> @alaneuler
> Thanks, only need to detect the specified environment variable in the `isLocalEnv` method?

To put it simple, say, user of SOFABoot add a configuration item `sofa.local.env=true` (for example, you can decide the key sensibly)  in `application.properties`, then method `isLocalEnv` always returns `true` no matter if it runs in Eclipse or IntelliJ IDEA or not.

**Comment by Darian1996** [comment]
- There is no need to modify `LogEnvironmentPrepareingListener#defaultConsoleLoggers()`

- `sofa.local.env=true` should be read and instantiate `LocalEnvUtil` field

- when  use `LocalEnvUtil#isLocalEnv` , 
  - first you shoud read this field 
  - second assert runs in Eclipse/IntelliJ IDEA or not.

- reason
  - this `LocalEnvUtil` not only used in `LogEnvironmentPrepareingListener` ，this is a universal static method , example if `LocalEnvUtil#isLocalEnv` return `true` , allows you to do things that are not allowed in the production environment.


- important 
  -  you should instantiate this `sofa.local.env=true` to LocalEnvUtil Before `LogEnviromnetPrepareingListener#defaultConsoleLoggers()`

**Comment by Darian1996** [comment]
- There is no need to modify `LogEnvironmentPrepareingListener#defaultConsoleLoggers()`

- `sofa.local.env=true` should be read and instantiate `LocalEnvUtil` field

- when  use `LocalEnvUtil#isLocalEnv` , 
  - first you shoud read this field 
  - second assert runs in Eclipse/IntelliJ IDEA or not.

- reason
  - this `LocalEnvUtil` not only used in `LogEnvironmentPrepareingListener` ，this is a universal static method , example if `LocalEnvUtil#isLocalEnv` return `true` , allows you to do things that are not allowed in the production environment.


- important 
  -  you should instantiate this `sofa.local.env=true` to LocalEnvUtil Before `LogEnviromnetPrepareingListener#defaultConsoleLoggers()`

**Comment by aaronlinv** [comment]
Thanks, all very helpful,  I resubmitted the code, is this ok?

**Comment by HzjNeverStop** [comment]
LocalEnvUtil 是作为静态类使用的，目前这种写法是无法注入配置的，你还有时间修复这段代码吗？

**Comment by aaronlinv** [comment]
> LocalEnvUtil 是作为静态类使用的，目前这种写法是无法注入配置的，你还有时间修复这段代码吗？

非常抱歉，目前在忙其他的事情，没有时间修复，请将对应的 issue 分配给其他的小伙伴

**Pull request closed without merging**
